### PR TITLE
Fix UI misbehavior

### LINKED ISSUE #10: UI issue with checkbox
In the task list page, when updating two or more tasks swiftly one after the other, the UI doesn't work as expected. tested on live network. i.e., if you try to check more than one checkbox one after the other immediately, only first task is checked. second one is unchecked but the status is updated as completed which is not correct.

But if you navigate to other page and return, the UI state is correct.

### LINKED ISSUE #12: exiting app using back button, returns to authentication page before exit - in non-mock

### PR DESCRIPTION
**Pull request by lionel1704**
- Create CommonViewModel with shared attributes and functions
- Extend CommonViewModel in all view models for consistent UI behavior

Fixes #10, fixes #12

### CODE REVIEW

**Comment by lionel1704** [comment]
@safesurfer I've made a few small changes to address certain concerns. Please review

File: app/src/main/java/net/maidsafe/sample/viewmodel/CommonViewModel.java [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+
+    private static final MutableLiveData<Boolean> CONNECTED = new MutableLiveData<>();
+    private static final MutableLiveData<Integer> STATUS = new MutableLiveData<>();;
+    private static String errorMessage;
+    protected final ITodoService todoService;
+
+
+    public CommonViewModel(final Application application) {
+        super(application);
+        STATUS.setValue(0);
```
Comment (krishnaIndia) [inline app/src/main/java/net/maidsafe/sample/viewmodel/CommonViewModel.java]: Is there something better that could be done rather than hard coding 0?

File: app/src/main/java/net/maidsafe/sample/viewmodel/CommonViewModel.java [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+import net.maidsafe.sample.services.IFailureHandler;
+import net.maidsafe.sample.services.IProgressHandler;
+import net.maidsafe.sample.services.ITodoService;
+import net.maidsafe.sample.services.OnDisconnected;
+import net.maidsafe.sample.services.Result;
+import net.maidsafe.sample.services.SafeTodoService;
+
+public class CommonViewModel extends AndroidViewModel implements IFailureHandler, IProgressHandler {
+
+    private static final MutableLiveData<Boolean> CONNECTED = new MutableLiveData<>();
```
Comment (krishnaIndia) [inline app/src/main/java/net/maidsafe/sample/viewmodel/CommonViewModel.java]: Isn't the naming conventions wrong here? Variables in capital casing refers to constant value.

File: app/src/main/java/net/maidsafe/sample/viewmodel/CommonViewModel.java [hunk 3]
```diff
@@ -0,0 +1,116 @@
...
+        super(application);
+        STATUS.setValue(0);
+        todoService = new SafeTodoService(application.getApplicationContext());
+    }
+
+    public void reconnect() {
+        new AsyncOperation(this).execute(() -> {
+            try {
+                todoService.reconnect();
+                return new Result(null);
```
Comment (krishnaIndia) [inline app/src/main/java/net/maidsafe/sample/viewmodel/CommonViewModel.java]: Better to have a default constructor instead of passing null as a parameter

File: app/src/main/java/net/maidsafe/sample/viewmodel/CommonViewModel.java (hunk 2 above)
Comment (lionel1704) [reply app/src/main/java/net/maidsafe/sample/viewmodel/CommonViewModel.java]: Yes @krishnaIndia. The MutableLiveData is a constant. We will be manipulating the Boolean it holds.
